// flow-typed signature: 6f34e61ef11781f7512c29167df8ce9f
// flow-typed version: <<STUB>>/date-fns_v1.29.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

// there is full declaration of date-fns in node_modules
// except it doesn't get picked up by flow for some reason
type Interval = {
  start: Date | string | number,
  end: Date | string | number
};

type Options = {
  weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6,
  additionalDigits?: 0 | 1 | 2,
  locale?: Locale,
  includeSeconds?: boolean,
  addSuffix?: boolean,
  unit?: "s" | "m" | "h" | "d" | "M" | "Y",
  roundingMethod?: "floor" | "ceil" | "round"
};

type Locale = {
  formatDistance: Function,
  formatLong: Function,
  formatRelative: Function,
  localize: {
    ordinalNumber: Function,
    weekday: Function,
    weekdays: Function,
    month: Function,
    months: Function,
    timeOfDay: Function,
    timesOfDay: Function
  },
  match: {
    ordinalNumbers: Function,
    ordinalNumber: Function,
    weekdays: Function,
    weekday: Function,
    months: Function,
    month: Function,
    timesOfDay: Function,
    timeOfDay: Function
  },
  formatters?: Object,
  formattingTokensRegExp?: RegExp,
  units?: Object,
  parsers?: Object,
  parsingTokensRegExp?: RegExp,
  options?: {
    weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6
  }
};

declare module "date-fns/format" {
  declare module.exports: (
    date: Date | string | number,
    format: string,
    options?: Options
  ) => string;
}
