/**
 * Flowtype definitions for createBrowserHistory
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

import { History } from "./index";
import { getConfirmation } from "./DOMUtils";

declare module 'history/createBrowserHistory' {
  declare export interface BrowserHistoryBuildOptions {
    basename?: string;
    forceRefresh?: boolean;
    getUserConfirmation?: typeof getConfirmation;
    keyLength?: number;
  }
  declare export default function createBrowserHistory(
    options?: BrowserHistoryBuildOptions
  ): History;
}
