/**
 * Flowtype definitions for DOMUtils
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export var isExtraneousPopstateEvent: boolean;
declare export function addEventListener(
  node: EventTarget,
  event: string,
  listener: EventListenerOrEventListenerObject
): void;
declare export function removeEventListener(
  node: EventTarget,
  event: string,
  listener: EventListenerOrEventListenerObject
): void;
declare export function getConfirmation(
  message: string,
  callback: (result: boolean) => void
): void;
declare export function supportsHistory(): boolean;
declare export function supportsGoWithoutReloadUsingHash(): boolean;
